#ifndef __CC2500_REGVAL_INCLUDED
#define __CC2500_REGVAL_INCLUDED

#include "cc2500_REG.h"
#include "cc2500_VAL.h"

byte cc2500_init_regval[] = {
	REG_IOCFG2   , VAL_IOCFG2,
	REG_IOCFG0   , VAL_IOCFG0,
	REG_PKTLEN   , VAL_PKTLEN,
	REG_PKTCTRL1 , VAL_PKTCTRL1,
	REG_PKTCTRL0 , VAL_PKTCTRL0,
	REG_ADDR     , VAL_ADDR,
	REG_CHANNR   , VAL_CHANNR,
	REG_FSCTRL1  , VAL_FSCTRL1,
	REG_FSCTRL0  , VAL_FSCTRL0,
	REG_FREQ2    , VAL_FREQ2,
	REG_FREQ1    , VAL_FREQ1,
	REG_FREQ0    , VAL_FREQ0,
	REG_MDMCFG4  , VAL_MDMCFG4,
	REG_MDMCFG3  , VAL_MDMCFG3,
	REG_MDMCFG2  , VAL_MDMCFG2,
	REG_MDMCFG1  , VAL_MDMCFG1,
	REG_MDMCFG0  , VAL_MDMCFG0,
	REG_DEVIATN  , VAL_DEVIATN,
	REG_MCSM2    , VAL_MCSM2,
	REG_MCSM1    , VAL_MCSM1,
	REG_MCSM0    , VAL_MCSM0,
	REG_FOCCFG   , VAL_FOCCFG,
	REG_BSCFG    , VAL_BSCFG,
	REG_AGCCTRL2 , VAL_AGCCTRL2,
	REG_AGCCTRL1 , VAL_AGCCTRL1,
	REG_AGCCTRL0 , VAL_AGCCTRL0,
	REG_WOREVT1  , VAL_WOREVT1,
	REG_WOREVT0  , VAL_WOREVT0,
	REG_WORCTRL  , VAL_WORCTRL,
	REG_FREND1   , VAL_FREND1,
	REG_FREND0   , VAL_FREND0,
	REG_FSCAL3   , VAL_FSCAL3,
	REG_FSCAL2   , VAL_FSCAL2,
	REG_FSCAL1   , VAL_FSCAL1,
	REG_FSCAL0   , VAL_FSCAL0,
	REG_RCCTRL1  , VAL_RCCTRL1,
	REG_RCCTRL0  , VAL_RCCTRL0,
	REG_FSTEST   , VAL_FSTEST,
	REG_TEST2    , VAL_TEST2,
	REG_TEST1    , VAL_TEST1,
	REG_TEST0    , VAL_TEST0,
	REG_DAFUQ    , VAL_DAFUQ
};

const int cc2500_init_regval_size = sizeof(cc2500_init_regval)/sizeof(cc2500_init_regval[0]);

#endif
